-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:c7ad1b6dd84f64b7a9c1975374b8ad36:828df3652e38c4c4402760730fb10a87:72aa0d6b74270cbdb556492258b9c42b$
-- 

return {
	texture = 'test2.png',
	frames = {
			{
				name = "chick_64x64.jpg",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
				uvRect = { u0 = 0, v0 = 0, u1 = 0.5, v1 = 0.25 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "mouse_64x64.jpg",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
				uvRect = { u0 = 0.5, v0 = 0, u1 = 1, v1 = 0.25 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pig_64x64.jpg",
				spriteColorRect = { x = 0, y = 0, width = 64, height = 64 },
				uvRect = { u0 = 0, v0 = 0.25, u1 = 0.5, v1 = 0.5 },
				spriteSourceSize = { width = 64, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "puppy_64x64.jpg",
				spriteColorRect = { x = 0, y = 0, width = 85, height = 64 },
				uvRect = { u0 = 0, v0 = 0.5, u1 = 0.664062, v1 = 0.75 },
				spriteSourceSize = { width = 85, height = 64 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

